### PR TITLE
Extended vCardArray parser

### PR DESCRIPTION
**Pull request by namper**
Added telephone parsing and removed parser coupling with vCardArray data

### CODE REVIEW

**Comment by meeb** [comment]
Thanks for the PR. Looks good, the only issue I can see is that using `TypedDict` and the typing will mandate at least Py3.8. This is probably fine, but worth mentioning.

**Comment by namper** [comment]
We can require [typing_extension](https://pypi.org/project/typing-extensions/) for 3.6-3.7

**Comment by meeb** [comment]
That would be an acceptable option. Do you want to add a patch to include `typing_extension`? If not I can add it before the next release.

**Comment by meeb** [comment]
Excellent, thanks! I'll bundle this into the next release in a day or two.

**Pull request merged**
