### PR TITLE
Add RIR : afnic

### PR DESCRIPTION
**Pull request by frntn**
Example use
```python
import whoisit
whoisit.bootstrap()
whoisit.entity('GAR109-FRNIC', rir='afnic')
```

### CODE REVIEW

**Comment by meeb** [comment]
This looks fine. Could you also add `AFNIC` to `RIR_ENTITY_PREFIXES` please? Then you wouldn't need to specify the `rir` manually either. Once you've done that I'll merge it. Thanks for the contribution!

**Comment by frntn** [comment]
Okay done @meeb ✅

**Comment by meeb** [comment]
Excellent, thanks!

**Comment by meeb** [comment]
This is merged into the 2.7.7 release available now.

**Pull request merged**
